project:
  type: website

website:
  title: "UT Austin SDS material summary"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: floating

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    toc-title: "On this page"
    toc-location: left
    number-sections: true

editor: visual
